// =============================================================================
// MakerPanel Rail System - T-Slot Compatible Modules
// Copyright (c) 2025 Ranch Hand Robotics, LLC. All rights reserved.
// Licensed under MIT License: https://opensource.org/licenses/MIT
// ============================================================================
// All rail modules use standard T-slot nuts for universal compatibility
// Supports M5/M6 T-slot twist nuts and drop-in T-nuts
// ============================================================================

include <common.scad>

// ============================================
// Helper: Rounded Square (2D)
// ============================================

module rounded_square(size, r=1) {
    /*
    Creates a 2D rectangle with rounded corners
    Parameters:
      - size: [width, height] or single value
      - r: corner radius
    */
    s = is_list(size) ? size : [size, size];
    r_clamped = min(r, min(s[0], s[1]) / 2);
    offset(r=r_clamped)
        offset(delta=-r_clamped)
            square(s, center=false);
}

// ============================================
// Module: T-Slot Horizontal Cross-Rail 2D Profile
// ============================================
// Generates the 2D cross-section profile that can be:
// - Extruded to create 3D rails
// - Exported as SVG/DXF for laser cutting

module maker_rail_2d(rail_width, height, mounting_holes=true, base=true) {
    /*
    Creates a 2D cross-section profile of the rail (X-Y plane)
    Parameters:
      - rail_width: rail length in mm
      - height: rail height in mm
      - mounting_holes: include mounting holes
    */

    rail_offset = mounting_holes? (-height/2) : 0;
    width = mounting_holes ? rail_width + height : rail_width;
    
    // Available space between mounting holes (equal spacing on both sides)
    available_space = mounting_holes ? (width - 2 * height) : (width - 2 * RACK_SUPPORT_WIDTH);
    
    // Calculate number of slots that fit with minimum spacing
    min_spacing = T_SLOT_WIDTH + RACK_SUPPORT_WIDTH;
    num_slots = floor((available_space + RACK_SUPPORT_WIDTH) / min_spacing);
    
    // Calculate minimum space needed
    min_space_needed = num_slots * T_SLOT_WIDTH + (num_slots - 1) * RACK_SUPPORT_WIDTH;
    
    // Calculate extra space and distribute proportionately among slots
    extra_space = available_space - min_space_needed;
    actual_slot_width = T_SLOT_WIDTH + (extra_space / num_slots);
    
    // First slot starts at height (equal distance from mounting hole to slot and hole to wall)
    first_slot_pos = mounting_holes ? height : RACK_SUPPORT_WIDTH;
    
    // Spacing between slots (center to center)
    actual_spacing = actual_slot_width + RACK_SUPPORT_WIDTH;
   
    difference() 
    {
        // Base rectangle (X-Y plane profile)
        if (base) {
            translate([rail_offset, -height/2])
                square([width, height], center=false);
        }
        
        // Cut T-slot compatible slots (rectangular cutouts with rounded corners)
        for (i = [0 : num_slots - 1]) {
            x_pos = first_slot_pos + i * actual_spacing;
            translate([x_pos + rail_offset, -T_SLOT_HEIGHT/2])
                rounded_square([actual_slot_width, T_SLOT_HEIGHT], r=T_SLOT_CORNER_RADIUS);
        }
        
        // Mounting holes on either side
        if (mounting_holes) {
            // Left mounting hole
            translate([height/2 + rail_offset, 0])
                circle(r=RACK_HOLE_DIAMETER/2, $fn=32);
            
            // Right mounting hole
            translate([width - height/2 + rail_offset, 0])
                circle(r=RACK_HOLE_DIAMETER/2, $fn=32);
        }
    }
}

// ============================================
// Module: T-Slot Horizontal Cross-Rail (3D)
// ============================================
// Uses standard T-slot twist nuts (drop-in compatible)
// Slot geometry sized for M5/M6 T-slot nuts

module maker_rail(rail_width, height=RACK_RAIL_HEIGHT, depth=RACK_RAIL_THICKNESS, mounting_holes=true) {
    /*
    Creates a horizontal cross-rail with T-slot twist nut compatibility
    Generated by extruding the 2D profile
    Parameters:
      - rail_width: rail length in mm
      - height: rail height in mm
      - depth: rail depth (front to back) in mm
      - mounting_holes: include mounting holes
    */
    linear_extrude(height=depth, center=true)
        maker_rail_2d(rail_width, height, mounting_holes);
}

// ============================================
// Module: Custom Width Maker Rack
// ============================================

module makerrack_custom(width, height) {
    /*
    Creates a rack with custom width
    Parameters:
      - width: outer width in mm
      - height: height in mm
    */
    
    rail_width = RACK_RAIL_HEIGHT;  // Using existing variable
    
    // Left rail - vertical, centered at x=0
    rotate([0, 0, 90])
        maker_rail(height, height=rail_width, depth=RACK_RAIL_THICKNESS, mounting_holes=false);
    
    // Right rail - vertical, centered at x=width
    translate([width - rail_width/2, 0, 0])
        rotate([0, 0, 90])
            maker_rail(height, height=rail_width, depth=RACK_RAIL_THICKNESS, mounting_holes=false);
}
